module.exports = {
  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    CONFLICT: 409,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
  },
  ERROR_CODES: {
    VALIDATION_ERROR: "VAL_ERR",
    AUTHENTICATION_ERROR: "AUTH_ERR",
    DATABASE_ERROR: "DB_ERR",
    NOT_FOUND_ERROR: "NOT_FOUND_ERR",
    RATE_LIMIT_ERROR: "RATE_LIMIT_ERR",
  },
};
